
name: TaskManager Workflow

jobs:

  build_and_push_backend_to_docker_hub:
    name: push Docker image with backend to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: deorz/task_manager_backend:latest

  build_and_push_frontend_to_docker_hub:
    name: push Docker image with frontend to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: deorz/task_manager_frontend:latest


  deploy:
    runs-on: ubuntu-latest
    needs:
      - build_and_push_backend_to_docker_hub
      - build_and_push_frontend_to_docker_hub
    if:
      contains('
      refs/heads/main
      refs/heads/master
      ', github.ref)
    steps:
      - uses: actions/checkout@v2
      - name: copy nginx and docker-compose to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "nginx.conf, docker-compose.yml"
          target: "~/task_manager"

      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd task_manager/
            docker pull deorz/task_manager_backend:latest
            docker pull deorz/task_manager_frontend:latest
            docker-compose up --force-recreate -d backend
